### PR TITLE
chore: regenerate with tree-sitter v0.22.6

### PR DESCRIPTION
**Pull request by clason**

### CODE REVIEW

**Comment by MichaHoffmann** [comment]
It doesnt fit perfectly but can you maybe also try to fix the contextType enum in the terraform scanner please?

**Comment by clason** [comment]
That is already fixed on `master`.

**Comment by MichaHoffmann** [comment]
> That is already fixed on `main`.

nvm, didnt see the push, sorry

**Review by MichaHoffmann — APPROVED** [review]
lgtm

**Pull request merged**
